### ISSUE TITLE
feat: 增加自托管地址配置的支持

### ISSUE THREAD

**Issue by acdiost** [funny-cat-happy/barknotificator#5]

**Comment by acdiost** [comment]
```python
bark = BarkNotificator(host="http(s)://ip:port", device_key="your device key")
```

**Comment by funny-cat-happy** [comment]
添加自托管的目的是什么呢，这已经可以直接和苹果服务器进行通信了

**Comment by acdiost** [comment]
自己部署的 bark-server 。
https://day.app/2018/06/bark-server-document/#bark%E6%98%AF%E5%95%A5 
目的：
>如果你的数据特别敏感，请将Bark部署到私人服务器。
所有的数据将只在 你的手机、你的服务器、Apple推送服务器之间传输。

**Comment by funny-cat-happy** [comment]
你对官方那个文档的理解有的错误，官方提供了两种实现方式，一种是发送给bark server，然后bark server再发送给苹果服务器，另一种就是文档里面说的通过命令行直接发送，无需添加服务器，我的这个包是对第二种方式的实现。第一种的话实现起来比较简单，自己发送请求就可以了，官方也不打算专门创建一个包

**Comment by acdiost** [comment]
是挺简单的，自己发个请求就可以了。
